# Generated by Django 3.2.4 on 2021-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seo_title', models.CharField(blank=True, max_length=300, null=True)),
                ('seo_image', models.URLField(blank=True, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=260, null=True)),
                ('custom_url', models.CharField(blank=True, max_length=300, null=True)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('short_url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'links',
                'ordering': ['-created'],
            },
        ),
    ]
